export const DRAFT_KEY = "milex.kam.recommendation.draft";

export const INITIAL_FORM = {
  identifier: "",
  accountName: "",
  primaryAddress: "",
  areaName: "",
  zoneName: "",
  mobileNumber: "",
  emailAddress: "",
  officePhone: "",
  faxNumber: "",
  businessType: "",
  serviceRequired: "",
  accountMode: "",
  accountType: "",
  creditLimit: "",
  creditPeriod: "",
  seniorName: "",
  seniorDesignation: "",
  seniorMobile: "",
  seniorEmail: "",
  keyName: "",
  keyDesignation: "",
  keyMobile: "",
  keyEmail: "",
  useKeyAsFinancial: false,
  financialName: "",
  financialDesignation: "",
  financialMobile: "",
  financialEmail: "",
  shipmentDocument: false,
  shipmentNonDocument: false,
  shipmentOthers: false,
  shipmentOtherText: "",
  rateFor: "",
  destinationCountry: "",
  monthlyVolume: "",
  monthlyWeight: "",
  monthlyRevenue: "",
  serviceProvider: "",
  additionalRoutes: [],
  recommendationNote: "",
};

export const STEPS = [
  "Basic Info",
  "Financial",
  "Contact Info",
  "Shipping Details",
  "Notes",
];
